# Generated by Django 4.2 on 2026-09-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scheduledmeeting_instructorname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='client@mind2i', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.URLField(blank=True, default='')),
                ('assignedBatches', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.RenameField(
            model_name='appsettingsmodel',
            old_name='enableZoomSync',
            new_name='enableClientPortal',
        ),
        migrations.RemoveField(
            model_name='appsettingsmodel',
            name='zoomConfig',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='registrationCode',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='zoomConfig',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='zoomLink',
        ),
        migrations.AddField(
            model_name='appsettingsmodel',
            name='defaultClientPassword',
            field=models.CharField(default='client@mind2i', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='durationMonths',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='batch',
            name='mentor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='programType',
            field=models.CharField(default='internship', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='githubUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='internshipEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internshipStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedinUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='resumeUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='appsettingsmodel',
            name='defaultStudentPassword',
            field=models.CharField(default='intern123', max_length=255),
        ),
        migrations.AlterField(
            model_name='batch',
            name='college',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='batch',
            name='durationLabel',
            field=models.CharField(default='3 Months', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(default='internship_3m', max_length=50),
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('requestedDate', models.DateTimeField(blank=True, null=True)),
                ('scheduledDate', models.DateTimeField(blank=True, null=True)),
                ('interviewType', models.CharField(default='virtual', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('adminNotes', models.TextField(blank=True, default='')),
                ('meetingLink', models.CharField(blank=True, default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='api.batch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='api.clientuser')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='api.student')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
