# Generated by Django 4.2 on 2026-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_clientuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
