# Generated by Django 4.2 on 2026-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_batch_islocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
