# Generated by Django 4.2 on 2026-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appnotification_attendancerecord_dailyactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resumeData',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
