# Generated by Django 4.2 on 2026-09-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_resumedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='batchName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='detailedInstructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='executiveSummary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='leaderboardPoints',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='mentorObservationBenchmark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='technicalCategory',
            field=models.CharField(blank=True, default='AI Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='demoVideoName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='demoVideoUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='fileName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='fileSize',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='githubRepoUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='gradePoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='mentorFeedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='submissionNotes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
